---
sudo: false
language: c
matrix:
  include:
    - env: TEST=markdownlint
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=make
      script: ./tests/make.sh

    - env: TEST=terraform
      services:
        - docker
      script: ./tests/terraform.sh

    - env: TEST=yamllint
      language: c
      services:
        - docker
      script: ./tests/yamllint.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
